export const googleFonts = [
  'Roboto',
  'Open Sans',
  'Lato',
  'Montserrat',
  'Oswald',
  'Source Sans Pro',
  'Slabo 27px',
  'Raleway',
  'PT Sans',
  'Merriweather',
  'Noto Sans',
  'Poppins',
  'Ubuntu',
  'Playfair Display',
  'Roboto Slab',
  'Arimo',
  'Nunito Sans',
  'Work Sans',
  'Fira Sans',
  'Lora',
  'Inter',
  'Quicksand',
  'Space Grotesk',
  'Source Code Pro',
  'IBM Plex Sans',
  'Titillium Web',
  'Karla',
  'Spectral',
  'Libre Franklin',
  'DM Sans',
];
