export const timezones = [
  { city: 'London', timezone: 'Europe/London', country: 'UK' },
  { city: 'Paris', timezone: 'Europe/Paris', country: 'France' },
  { city: 'Berlin', timezone: 'Europe/Berlin', country: 'Germany' },
  { city: 'Moscow', timezone: 'Europe/Moscow', country: 'Russia' },
  { city: 'New York', timezone: 'America/New_York', country: 'USA' },
  { city: 'Chicago', timezone: 'America/Chicago', country: 'USA' },
  { city: 'Denver', timezone: 'America/Denver', country: 'USA' },
  { city: 'Los Angeles', timezone: 'America/Los_Angeles', country: 'USA' },
  { city: 'Tokyo', timezone: 'Asia/Tokyo', country: 'Japan' },
  { city: 'Shanghai', timezone: 'Asia/Shanghai', country: 'China' },
  { city: 'Hong Kong', timezone: 'Asia/Hong_Kong', country: 'China' },
  { city: 'Singapore', timezone: 'Asia/Singapore', country: 'Singapore' },
  { city: 'Dubai', timezone: 'Asia/Dubai', country: 'UAE' },
  { city: 'Sydney', timezone: 'Australia/Sydney', country: 'Australia' },
  { city: 'Melbourne', timezone: 'Australia/Melbourne', country: 'Australia' },
  { city: 'Auckland', timezone: 'Pacific/Auckland', country: 'New Zealand' },
  { city: 'Sao Paulo', timezone: 'America/Sao_Paulo', country: 'Brazil' },
  { city: 'Buenos Aires', timezone: 'America/Argentina/Buenos_Aires', country: 'Argentina' },
  { city: 'Cairo', timezone: 'Africa/Cairo', country: 'Egypt' },
  { city: 'Johannesburg', timezone: 'Africa/Johannesburg', country: 'South Africa' },
  { city: 'Lagos', timezone: 'Africa/Lagos', country: 'Nigeria' },
  { city: 'Kolkata', timezone: 'Asia/Kolkata', country: 'India' },
  { city: 'Seoul', timezone: 'Asia/Seoul', country: 'South Korea' },
  { city: 'Jakarta', timezone: 'Asia/Jakarta', country: 'Indonesia' },
  { city: 'Toronto', timezone: 'America/Toronto', country: 'Canada' },
  { city: 'Vancouver', timezone: 'America/Vancouver', country: 'Canada' },
  { city: 'Mexico City', timezone: 'America/Mexico_City', country: 'Mexico' },
  { city: 'Istanbul', timezone: 'Europe/Istanbul', country: 'Turkey' },
  { city: 'Riyadh', timezone: 'Asia/Riyadh', country: 'Saudi Arabia' },
  { city: 'Tehran', timezone: 'Asia/Tehran', country: 'Iran' },
  { city: 'Karachi', timezone: 'Asia/Karachi', country: 'Pakistan' },
  { city: 'Bangkok', timezone: 'Asia/Bangkok', country: 'Thailand' },
  { city: 'Manila', timezone: 'Asia/Manila', country: 'Philippines' },
  { city: 'Honolulu', timezone: 'Pacific/Honolulu', country: 'USA' },
  { city: 'Anchorage', timezone: 'America/Anchorage', country: 'USA' },
  { city: 'Reykjavik', timezone: 'Atlantic/Reykjavik', country: 'Iceland' },
];
